# Generated by Django 4.0.3 on 2022-04-19 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.br.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nome', models.CharField(blank=True, max_length=255, verbose_name='Nome Completo')),
                ('username', models.CharField(max_length=35, unique=True, verbose_name='Nome de Usuário')),
                ('email', models.CharField(max_length=255, unique=True, verbose_name='Endereço de e-mail')),
                ('tel', models.CharField(blank=True, max_length=15, verbose_name='Número de Telefone')),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Conta',
            },
        ),
        migrations.CreateModel(
            name='UserEndereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_nomecompleto', models.CharField(max_length=150, verbose_name='Número de Telefone')),
                ('en_tel', models.CharField(blank=True, max_length=15, verbose_name='Número de Telefone')),
                ('en_cep', localflavor.br.models.BRPostalCodeField(max_length=9, verbose_name='CEP')),
                ('en_rua', models.CharField(max_length=255, verbose_name='Rua')),
                ('en_bairro', models.CharField(max_length=35, verbose_name='Bairro')),
                ('en_cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('en_estado', localflavor.br.models.BRStateField(max_length=2, verbose_name='Estado')),
                ('en_compl', models.CharField(blank=True, max_length=255, verbose_name='Complemento')),
                ('default', models.BooleanField(default=False, verbose_name='Padrão')),
                ('en_criado', models.DateTimeField(auto_now_add=True)),
                ('en_atualizado', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Endereço',
            },
        ),
    ]
