# Generated by Django 4.0.3 on 2022-04-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userendereco',
            name='en_nomecompleto',
            field=models.CharField(max_length=150, verbose_name='Nome Completo'),
        ),
    ]
