# Generated by Django 4.0.5 on 2022-06-21 22:53

from django.db import migrations, models
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0002_alter_userendereco_en_nomecompleto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userendereco',
            name='en_cep',
            field=localflavor.br.models.BRPostalCodeField(help_text='Preencha no formato: XXXXX-XXX', max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='userendereco',
            name='en_rua',
            field=models.CharField(help_text='Incluindo o número', max_length=255, verbose_name='Rua'),
        ),
    ]
