# Generated by Django 4.0.5 on 2022-06-25 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aquaflorastore', '0011_remove_produto_livro_qtdd_alter_categoria_cat_ativa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_wishlist', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('wishlist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Item_Favoritado', to='aquaflorastore.produto')),
            ],
        ),
    ]
