# Generated by Django 4.0.3 on 2022-04-19 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_nome', models.CharField(db_index=True, max_length=255, verbose_name='Categoria')),
                ('cat_slug', models.SlugField(max_length=255, unique=True)),
                ('cat_ativa', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cat_criadoem', models.DateTimeField(auto_now_add=True, verbose_name='Criado em:')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livro_nome', models.CharField(max_length=255, verbose_name='Nome do livro')),
                ('livro_autor', models.CharField(max_length=255, verbose_name='Autor do Livro')),
                ('livro_desc', models.TextField(blank=True, verbose_name='Descrição')),
                ('livro_editora', models.CharField(max_length=255, verbose_name='Editora')),
                ('livro_ano', models.CharField(max_length=255, verbose_name='Ano')),
                ('livro_qtdd', models.PositiveSmallIntegerField(verbose_name='Quantidade Disponível')),
                ('livro_idioma', models.CharField(max_length=255, verbose_name='Idioma')),
                ('livro_acab', models.CharField(max_length=255, verbose_name='Acabamento')),
                ('img_1', models.ImageField(default='images/Default01.jpg', upload_to='images/')),
                ('img_2', models.ImageField(default='images/Default01.jpg', upload_to='images/')),
                ('img_3', models.ImageField(default='images/Default01.jpg', upload_to='images/')),
                ('livro_preco', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço')),
                ('livro_slug', models.SlugField(max_length=255)),
                ('livro_ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('livro_estoque', models.BooleanField(default=True, verbose_name='Em Estoque')),
                ('livro_BS', models.BooleanField(default=False, verbose_name='Best Seller')),
                ('livro_NEW', models.BooleanField(default=False, verbose_name='Lançamento')),
                ('livro_PROMO', models.BooleanField(default=False, verbose_name='Promoção')),
                ('livro_criadoem', models.DateTimeField(auto_now_add=True, verbose_name='Criado em:')),
                ('livro_atualizadoem', models.DateTimeField(auto_now=True, verbose_name='Atualizado em:')),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Produto', to='aquaflorastore.categoria')),
            ],
            options={
                'ordering': ('-livro_criadoem',),
            },
        ),
    ]
