# Generated by Django 4.0.3 on 2022-04-19 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aquaflorastore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='Criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='criador_instancia', to=settings.AUTH_USER_MODEL),
        ),
    ]
