# Generated by Django 4.0.3 on 2022-05-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaflorastore', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='img_2',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='img_3',
        ),
        migrations.AlterField(
            model_name='produto',
            name='livro_preco',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço - Lembre-se de considerar as taxas do MercadoPago (5%)'),
        ),
    ]
