# Generated by Django 4.0.3 on 2022-05-09 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aquaflorastore', '0005_alter_categoria_created_by_alter_produto_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='criador_categoria', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='produto',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='criador_produto', to=settings.AUTH_USER_MODEL),
        ),
    ]
