# Generated by Django 4.0.4 on 2022-05-30 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquaflorastore', '0006_alter_categoria_created_by_alter_produto_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Relatório de Estoque',
                'verbose_name_plural': 'Relatórios de Estoque',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aquaflorastore.produto',),
        ),
    ]
