# Generated by Django 4.0.4 on 2022-05-31 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquaflorastore', '0007_produtoproxy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProdutoProxy',
        ),
    ]
