# Generated by Django 4.0.5 on 2022-06-21 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aquaflorastore', '0008_delete_produtoproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movimentado_em', models.DateTimeField(auto_now=True)),
                ('quantidade', models.IntegerField(default=0, verbose_name='quantidade')),
                ('movimentado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='movimentado_por')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aquaflorastore.produto', verbose_name='produto')),
            ],
        ),
    ]
