# Generated by Django 4.0.5 on 2022-06-21 00:11

from django.db import migrations

# https://docs.djangoproject.com/en/4.0/ref/migration-operations/#django.db.migrations.operations.RunPython
def preencher_estoque(apps, schema_editor):
    Produto = apps.get_model("aquaflorastore", "Produto")
    ProdutoEstoque = apps.get_model("aquaflorastore", "ProdutoEstoque")
    Pedido = apps.get_model("pedidos", "Pedido")

    for produto in Produto.objects.all():
        movimentacao = ProdutoEstoque(
            produto=produto,
            quantidade=produto.livro_qtdd,
            movimentado_em=produto.livro_criadoem,
            movimentado_por=produto.created_by,
        )
        movimentacao.save()

    pedido_queryset = Pedido.objects.filter(statusentrega__in=("ENCM",))
    for pedido in pedido_queryset:
        for item in pedido.Itens.all():
            movimentacao = ProdutoEstoque(
                produto=item.produto,
                quantidade=-item.qtdd,
                movimentado_em=pedido.criadoem,
                movimentado_por=pedido.user,
            )
            movimentacao.save()


class Migration(migrations.Migration):

    dependencies = [
        ("aquaflorastore", "0009_produtoestoque"),
        ("pedidos", "0019_alter_pedido_statuspgto"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="produtoestoque",
            options={
                "verbose_name": "Movimentação de Estoque",
                "verbose_name_plural": "Movimentações de Estoque",
            },
        ),
        migrations.RunPython(preencher_estoque, migrations.RunPython.noop),
    ]
