# Generated by Django 4.0.5 on 2022-06-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaflorastore', '0010_preparar_estoque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='livro_qtdd',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='cat_ativa',
            field=models.BooleanField(default=True, help_text='Marque como falso caso queira arquivar a categoria.', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='livro_BS',
            field=models.BooleanField(default=False, help_text='Marque essa opção como verdadeira de acordo com os relatórios de vendas.', verbose_name='Popular/Mais Vendido'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='livro_ativo',
            field=models.BooleanField(default=True, help_text='Marque como falso caso queira arquivar esse produto.', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='livro_preco',
            field=models.DecimalField(decimal_places=2, help_text='Considere as taxas do Mercado Pago sobre pagamentos ao estabelecer o preço.', max_digits=6, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='produtoestoque',
            name='quantidade',
            field=models.IntegerField(default=0, help_text='Importante: Ao retirar exemplares do estoque, utilize números negativos. Ao adicionar exemplares, utilize números positivos.', verbose_name='quantidade'),
        ),
    ]
