# Generated by Django 4.0.3 on 2022-04-19 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.br.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aquaflorastore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userCPF', localflavor.br.models.BRCPFField(max_length=14, verbose_name='CPF')),
                ('userNome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('criadoem', models.DateTimeField(auto_now_add=True, verbose_name='Criado em:')),
                ('valorpgto', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor Total')),
                ('statuspgto', models.BooleanField(default=False, verbose_name='Status do pagamento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_pedido', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('userEnderecoEntrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_endereco', to='conta.userendereco', verbose_name='Endereço de Entrega')),
            ],
            options={
                'ordering': ('-criadoem',),
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('qtdd', models.PositiveIntegerField(default=1)),
                ('pedidoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Itens', to='pedidos.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Itens', to='aquaflorastore.produto')),
            ],
        ),
    ]
