# Generated by Django 4.0.3 on 2022-04-26 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_remove_pedido_usercpf_pedido_userfrete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='userEnderecoEntrega',
            field=models.CharField(max_length=255, verbose_name='Endereço de Entrega'),
        ),
    ]
