# Generated by Django 4.0.3 on 2022-04-26 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0002_alter_userendereco_en_nomecompleto'),
        ('pedidos', '0004_alter_pedido_userenderecoentrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='userEnderecoEntrega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_endereco', to='conta.userendereco', verbose_name='Endereço de Entrega'),
        ),
    ]
