# Generated by Django 4.0.3 on 2022-04-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_alter_pedido_userenderecoentrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='statusentrega',
            field=models.BooleanField(default=False, verbose_name='Status de Entrega'),
        ),
    ]
