# Generated by Django 4.0.3 on 2022-05-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_pedido_statusentrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='statuscancelado',
            field=models.BooleanField(default=False, verbose_name='Cancelado'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='statusreembolso',
            field=models.BooleanField(default=False, verbose_name='Reembolso'),
        ),
    ]
