# Generated by Django 4.0.4 on 2022-05-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_alter_pedido_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='statuscancelado',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='statusreembolso',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='statusentrega',
            field=models.CharField(choices=[('PROC', 'Processando Pedido'), ('ENCM', 'Pacote Encaminhado'), ('ENTR', 'Pacote Entregue'), ('DEVV', 'Pacote Devolvido'), ('ESTR', 'Pacote Estraviado')], default='PROC', max_length=100),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='statuspgto',
            field=models.CharField(choices=[('APRV', 'Pagamento Aprovado'), ('PEND', 'Pagamento Pendente'), ('CANC', 'Pedido Cancelado'), ('ESTR', 'Estornado')], default='PEND', max_length=100),
        ),
    ]
