# Generated by Django 4.0.4 on 2022-05-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_remove_pedido_statuscancelado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='payment_id',
            field=models.CharField(default='Unknown', max_length=255, verbose_name='ID do Pagamento'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='preference_id',
            field=models.CharField(default='Unknown', max_length=255, verbose_name='ID da Preferência'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='statuspgto',
            field=models.CharField(choices=[('APRV', 'Pagamento Aprovado'), ('PEND', 'Pagamento Pendente'), ('CANC', 'Pedido Cancelado'), ('ESTR', 'Estornado'), ('REJC', 'Rejeitado'), ('DISP', 'Disputado')], default='PEND', max_length=100),
        ),
    ]
