# Generated by Django 4.0.4 on 2022-05-30 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquaflorastore', '0007_produtoproxy'),
        ('pedidos', '0012_pedido_payment_id_pedido_preference_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaisVendidos',
            fields=[
            ],
            options={
                'verbose_name': 'Mais vendidos',
                'verbose_name_plural': 'Mais Vendidos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aquaflorastore.produto',),
        ),
        migrations.CreateModel(
            name='PedidoProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Relatório de Vendas',
                'verbose_name_plural': 'Relatórios de Vendas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pedidos.pedido',),
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ('-criadoem',), 'verbose_name': 'Pedido'},
        ),
    ]
