# Generated by Django 4.0.4 on 2022-05-31 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0013_maisvendidos_pedidoproxy_alter_pedido_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaisVendidos',
        ),
        migrations.DeleteModel(
            name='PedidoProxy',
        ),
    ]
