# Generated by Django 4.0.5 on 2022-06-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0014_delete_maisvendidos_delete_pedidoproxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valorpgto',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=9, verbose_name='Valor Total'),
        ),
    ]
