# Generated by Django 4.0.5 on 2022-06-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0017_alter_pedido_criadoem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='statusentrega',
            field=models.CharField(choices=[('PROC', 'Processando Pedido'), ('ENCM', 'Pacote Encaminhado'), ('ENTR', 'Pacote Entregue'), ('DEVV', 'Pacote Devolvido'), ('ESTR', 'Pacote Estraviado'), ('CANC', 'Pedido Cancelado Antes de Enviar')], default='PROC', max_length=100),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='statuspgto',
            field=models.CharField(choices=[('APRV', 'Pagamento Aprovado'), ('PEND', 'Pagamento Pendente'), ('CANC', 'Pedido Cancelado Antes de Pagar'), ('CANP', 'Estorno em Processamento'), ('ESTR', 'Estornado'), ('REJC', 'Rejeitado'), ('DISP', 'Disputado')], default='PEND', max_length=100),
        ),
    ]
