# Generated by Django 4.0.5 on 2022-06-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0018_alter_pedido_statusentrega_alter_pedido_statuspgto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='statuspgto',
            field=models.CharField(choices=[('APRV', 'Pagamento Aprovado'), ('PEND', 'Pagamento Pendente'), ('CANC', 'Pedido Cancelado Antes de Pagar'), ('CANP', 'Estorno em Processamento'), ('REJC', 'Estornado'), ('ESTR', 'Rejeitado'), ('DISP', 'Disputado')], default='PEND', max_length=100),
        ),
    ]
