# Generated by Django 4.0.3 on 2022-04-19 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpcoesFrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FreteNome', models.CharField(help_text='Obrigatório', max_length=255, verbose_name='Tipo de Frete')),
                ('FretePreco', models.DecimalField(decimal_places=2, help_text='Máximo R$ 999.99', max_digits=5, verbose_name='Preço do Frete')),
                ('FreteTempoAprox', models.CharField(help_text='Obrigatório', max_length=255, verbose_name='Tempo Aproximado')),
                ('Frete_Ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Opção de Frete',
                'verbose_name_plural': 'Opções de Frete',
            },
        ),
    ]
