# Generated by Django 4.0.5 on 2022-06-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaflora_checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcoesfrete',
            name='FreteNome',
            field=models.CharField(max_length=255, verbose_name='Tipo de Frete'),
        ),
        migrations.AlterField(
            model_name='opcoesfrete',
            name='FretePreco',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço do Frete'),
        ),
        migrations.AlterField(
            model_name='opcoesfrete',
            name='FreteTempoAprox',
            field=models.CharField(help_text='Recomenda-se que adicione um dia a mais na previsão.', max_length=255, verbose_name='Tempo Aproximado'),
        ),
        migrations.AlterField(
            model_name='opcoesfrete',
            name='Frete_Ativo',
            field=models.BooleanField(default=True, help_text='Marque como falso caso queira esconder a opção.'),
        ),
    ]
